### ISSUE TITLE
Notification module with Mendix 7 and different layouts keeps pushing messages

### ISSUE THREAD

**Issue by Mcpoowl** [appronto/Appronto-Notification-Module#2]
When the Appronto Notification module is in each layout, and in your app you switch to a page with a different layout, the notification module keeps pushing it's last message, even though it has nothing to do with the context.

@pimvdnoll remember our talk about this? :-)

//edit: If you use the same layout on every page, the problem does not occur, but that's not a valid solution for our app unfortunately

**Comment by pimvdnoll** [comment]
yes I remember ;)
maybe nanoflows can be used, let's see

**Comment by Mcpoowl** [comment]
I managed to resolve the issue by using the widget's On Click and On Timeout properties to call a microflow and delete the notification object.

**Comment by pimvdnoll** [comment]
Awesome @Mcpoowl good find!! will update the module asap.
